version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: production
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
